version: '3.8'

services: 
  ansible-host:
    hostname: ansible-host 
    build: .
    container_name: ansible-host 
    volumes: 
      - ./roles:/etc/ansible/roles 
      - ./playbook.yml:/etc/ansible/playbook.yml 
      - ./inventory.ini:/etc/ansible/inventory.ini
      - ./ansible.cfg:/etc/ansible/ansible.cfg     
      - ./run_playbook.sh:/usr/local/bin/run_playbook.sh 
    command: ["sudo", "./usr/local/bin/run_playbook.sh"]
    networks:
      - ansible_k3s

  ansible-agent:
    hostname: ansible-agent
    container_name: ansible-agent 
    build:
      context: .
      dockerfile: Dockerfile.agent
    environment:
      SSH_USERNAME: doron
      SSH_USERPASS: doron
    command: ["sudo", "/usr/sbin/sshd", "-D"]
    networks:
      - ansible_k3s

networks:
  ansible_k3s:
    driver: bridge
